// Supplement Catalog and Wellness Goals for Glowera
import { SupplementInfo, WellnessGoalInfo, WellnessGoal } from '../types/supplement';

export const WELLNESS_GOALS: WellnessGoalInfo[] = [
  {
    id: 'energy',
    name: 'Energy',
    icon: '⚡',
    description: 'Boost vitality and reduce fatigue',
  },
  {
    id: 'sleep',
    name: 'Sleep',
    icon: '🌙',
    description: 'Improve sleep quality and relaxation',
  },
  {
    id: 'immunity',
    name: 'Immunity',
    icon: '🛡️',
    description: 'Support immune system health',
  },
  {
    id: 'digestion',
    name: 'Digestion',
    icon: '🌿',
    description: 'Promote gut health and digestion',
  },
  {
    id: 'skin-health',
    name: 'Skin Health',
    icon: '✨',
    description: 'Nourish skin from within',
  },
  {
    id: 'stress-relief',
    name: 'Stress Relief',
    icon: '🧘',
    description: 'Calm mind and reduce stress',
  },
  {
    id: 'focus',
    name: 'Focus',
    icon: '🎯',
    description: 'Enhance mental clarity and concentration',
  },
  {
    id: 'general-wellness',
    name: 'General Wellness',
    icon: '💜',
    description: 'Overall health and well-being',
  },
];

export const SUPPLEMENT_CATEGORIES = [
  { id: 'vitamins', name: 'Vitamins', icon: '💊' },
  { id: 'minerals', name: 'Minerals', icon: '🔶' },
  { id: 'omega-fatty-acids', name: 'Omega Fatty Acids', icon: '🐟' },
  { id: 'probiotics', name: 'Probiotics', icon: '🦠' },
  { id: 'herbal', name: 'Herbal', icon: '🌿' },
  { id: 'specialty', name: 'Specialty', icon: '⭐' },
] as const;

export const SUPPLEMENT_CATALOG: SupplementInfo[] = [
  // VITAMINS
  {
    id: 'vitamin-d3',
    name: 'Vitamin D3',
    icon: '☀️',
    category: 'vitamins',
    description: 'The sunshine vitamin that supports bone health, immune function, and mood regulation.',
    benefits: ['Bone health', 'Immune support', 'Mood balance'],
    typicalDosage: '1000-5000 IU daily',
    timing: 'morning',
    tags: ['immunity', 'energy', 'general-wellness'],
  },
  {
    id: 'vitamin-c',
    name: 'Vitamin C',
    icon: '🍊',
    category: 'vitamins',
    description: 'A powerful antioxidant that supports immune health and collagen production.',
    benefits: ['Immune boost', 'Skin health', 'Antioxidant'],
    typicalDosage: '500-1000mg daily',
    timing: 'any',
    tags: ['immunity', 'skin-health', 'general-wellness'],
  },
  {
    id: 'vitamin-b12',
    name: 'Vitamin B12',
    icon: '🔴',
    category: 'vitamins',
    description: 'Essential for energy production, brain function, and red blood cell formation.',
    benefits: ['Energy boost', 'Brain health', 'Nerve function'],
    typicalDosage: '500-1000mcg daily',
    timing: 'morning',
    tags: ['energy', 'focus', 'general-wellness'],
  },
  {
    id: 'vitamin-b-complex',
    name: 'B-Complex',
    icon: '🌈',
    category: 'vitamins',
    description: 'A blend of B vitamins supporting energy metabolism and nervous system health.',
    benefits: ['Energy metabolism', 'Stress support', 'Nervous system'],
    typicalDosage: '1 capsule daily',
    timing: 'morning',
    tags: ['energy', 'stress-relief', 'focus'],
  },
  {
    id: 'vitamin-e',
    name: 'Vitamin E',
    icon: '🌻',
    category: 'vitamins',
    description: 'An antioxidant that protects cells and supports skin health.',
    benefits: ['Skin protection', 'Cell health', 'Antioxidant'],
    typicalDosage: '400 IU daily',
    timing: 'with-food',
    tags: ['skin-health', 'general-wellness'],
  },
  {
    id: 'vitamin-k2',
    name: 'Vitamin K2',
    icon: '💚',
    category: 'vitamins',
    description: 'Supports calcium metabolism for healthy bones and cardiovascular function.',
    benefits: ['Bone density', 'Heart health', 'Calcium transport'],
    typicalDosage: '100-200mcg daily',
    timing: 'with-food',
    tags: ['general-wellness'],
  },
  {
    id: 'vitamin-a',
    name: 'Vitamin A',
    icon: '🥕',
    category: 'vitamins',
    description: 'Essential for vision, immune function, and skin health.',
    benefits: ['Eye health', 'Immune support', 'Skin renewal'],
    typicalDosage: '5000 IU daily',
    timing: 'with-food',
    tags: ['immunity', 'skin-health', 'general-wellness'],
  },
  {
    id: 'folate',
    name: 'Folate (B9)',
    icon: '🥬',
    category: 'vitamins',
    description: 'Essential for cell division and DNA synthesis, important for prenatal health.',
    benefits: ['Cell growth', 'Energy', 'Mood support'],
    typicalDosage: '400-800mcg daily',
    timing: 'any',
    tags: ['energy', 'general-wellness'],
  },
  {
    id: 'biotin',
    name: 'Biotin',
    icon: '💅',
    category: 'vitamins',
    description: 'Supports healthy hair, skin, and nails by aiding keratin production.',
    benefits: ['Hair growth', 'Nail strength', 'Skin health'],
    typicalDosage: '2500-5000mcg daily',
    timing: 'any',
    tags: ['skin-health'],
  },

  // MINERALS
  {
    id: 'magnesium',
    name: 'Magnesium',
    icon: '🧲',
    category: 'minerals',
    description: 'A relaxation mineral that supports muscle function, sleep, and stress management.',
    benefits: ['Better sleep', 'Muscle relaxation', 'Stress relief'],
    typicalDosage: '200-400mg daily',
    timing: 'evening',
    tags: ['sleep', 'stress-relief', 'general-wellness'],
  },
  {
    id: 'magnesium-glycinate',
    name: 'Magnesium Glycinate',
    icon: '😴',
    category: 'minerals',
    description: 'A highly absorbable form of magnesium, especially good for sleep and anxiety.',
    benefits: ['Deep sleep', 'Calm nerves', 'Gentle on stomach'],
    typicalDosage: '200-400mg daily',
    timing: 'evening',
    tags: ['sleep', 'stress-relief'],
  },
  {
    id: 'zinc',
    name: 'Zinc',
    icon: '🔷',
    category: 'minerals',
    description: 'An essential mineral for immune function, wound healing, and skin health.',
    benefits: ['Immune defense', 'Skin healing', 'Cellular repair'],
    typicalDosage: '15-30mg daily',
    timing: 'with-food',
    tags: ['immunity', 'skin-health', 'general-wellness'],
  },
  {
    id: 'iron',
    name: 'Iron',
    icon: '🩸',
    category: 'minerals',
    description: 'Critical for oxygen transport and energy production in the body.',
    benefits: ['Energy levels', 'Oxygen transport', 'Cognitive function'],
    typicalDosage: '18mg daily (varies)',
    timing: 'morning',
    tags: ['energy', 'focus', 'general-wellness'],
  },
  {
    id: 'calcium',
    name: 'Calcium',
    icon: '🦴',
    category: 'minerals',
    description: 'Essential for strong bones, teeth, and muscle function.',
    benefits: ['Bone strength', 'Muscle function', 'Nerve signaling'],
    typicalDosage: '500-1000mg daily',
    timing: 'with-food',
    tags: ['general-wellness'],
  },
  {
    id: 'selenium',
    name: 'Selenium',
    icon: '🌰',
    category: 'minerals',
    description: 'A trace mineral with powerful antioxidant properties supporting thyroid health.',
    benefits: ['Thyroid support', 'Antioxidant', 'Immune function'],
    typicalDosage: '55-200mcg daily',
    timing: 'with-food',
    tags: ['immunity', 'general-wellness'],
  },
  {
    id: 'potassium',
    name: 'Potassium',
    icon: '🍌',
    category: 'minerals',
    description: 'Important for heart health, muscle function, and fluid balance.',
    benefits: ['Heart health', 'Muscle function', 'Electrolyte balance'],
    typicalDosage: '99-600mg daily',
    timing: 'with-food',
    tags: ['energy', 'general-wellness'],
  },

  // OMEGA FATTY ACIDS
  {
    id: 'omega-3',
    name: 'Omega-3 Fish Oil',
    icon: '🐟',
    category: 'omega-fatty-acids',
    description: 'Essential fatty acids supporting heart, brain, and joint health.',
    benefits: ['Heart health', 'Brain function', 'Joint mobility'],
    typicalDosage: '1000-2000mg EPA/DHA daily',
    timing: 'with-food',
    tags: ['focus', 'general-wellness'],
  },
  {
    id: 'algae-omega',
    name: 'Algae Omega-3',
    icon: '🌊',
    category: 'omega-fatty-acids',
    description: 'Plant-based DHA and EPA from algae, great for vegetarians.',
    benefits: ['Brain health', 'Eye health', 'Plant-based'],
    typicalDosage: '250-500mg DHA daily',
    timing: 'with-food',
    tags: ['focus', 'general-wellness'],
  },
  {
    id: 'evening-primrose-oil',
    name: 'Evening Primrose Oil',
    icon: '🌸',
    category: 'omega-fatty-acids',
    description: 'Rich in GLA, supporting hormonal balance and skin health.',
    benefits: ['Hormone balance', 'Skin nourishment', 'PMS support'],
    typicalDosage: '500-1000mg daily',
    timing: 'with-food',
    tags: ['skin-health', 'general-wellness'],
  },
  {
    id: 'flaxseed-oil',
    name: 'Flaxseed Oil',
    icon: '🌾',
    category: 'omega-fatty-acids',
    description: 'Plant-based omega-3 (ALA) supporting heart and digestive health.',
    benefits: ['Heart health', 'Digestive support', 'Skin moisture'],
    typicalDosage: '1000-2000mg daily',
    timing: 'with-food',
    tags: ['digestion', 'skin-health'],
  },

  // PROBIOTICS
  {
    id: 'probiotic-blend',
    name: 'Probiotic Blend',
    icon: '🦠',
    category: 'probiotics',
    description: 'A multi-strain probiotic supporting gut health and immune function.',
    benefits: ['Gut health', 'Immune support', 'Digestive comfort'],
    typicalDosage: '10-50 billion CFU daily',
    timing: 'morning',
    tags: ['digestion', 'immunity', 'general-wellness'],
  },
  {
    id: 'lactobacillus',
    name: 'Lactobacillus',
    icon: '🥛',
    category: 'probiotics',
    description: 'Beneficial bacteria supporting digestive health and nutrient absorption.',
    benefits: ['Digestive health', 'Lactose tolerance', 'Gut balance'],
    typicalDosage: '1-10 billion CFU daily',
    timing: 'morning',
    tags: ['digestion', 'general-wellness'],
  },
  {
    id: 'bifidobacterium',
    name: 'Bifidobacterium',
    icon: '🧫',
    category: 'probiotics',
    description: 'Supports intestinal health and helps maintain a healthy gut barrier.',
    benefits: ['Intestinal health', 'Immune balance', 'Regularity'],
    typicalDosage: '1-10 billion CFU daily',
    timing: 'morning',
    tags: ['digestion', 'immunity'],
  },
  {
    id: 'prebiotic-fiber',
    name: 'Prebiotic Fiber',
    icon: '🌱',
    category: 'probiotics',
    description: 'Feeds beneficial gut bacteria, promoting a healthy microbiome.',
    benefits: ['Gut bacteria food', 'Regularity', 'Microbiome support'],
    typicalDosage: '5-10g daily',
    timing: 'any',
    tags: ['digestion', 'general-wellness'],
  },

  // HERBAL
  {
    id: 'ashwagandha',
    name: 'Ashwagandha',
    icon: '🌿',
    category: 'herbal',
    description: 'An adaptogen that helps the body manage stress and promotes calm energy.',
    benefits: ['Stress adaptation', 'Energy balance', 'Calm focus'],
    typicalDosage: '300-600mg daily',
    timing: 'evening',
    tags: ['stress-relief', 'energy', 'sleep'],
  },
  {
    id: 'rhodiola',
    name: 'Rhodiola Rosea',
    icon: '🏔️',
    category: 'herbal',
    description: 'An adaptogen supporting mental performance and physical endurance.',
    benefits: ['Mental clarity', 'Physical endurance', 'Stress resilience'],
    typicalDosage: '200-400mg daily',
    timing: 'morning',
    tags: ['energy', 'focus', 'stress-relief'],
  },
  {
    id: 'turmeric',
    name: 'Turmeric/Curcumin',
    icon: '🧡',
    category: 'herbal',
    description: 'A powerful anti-inflammatory spice supporting joint and brain health.',
    benefits: ['Anti-inflammatory', 'Joint comfort', 'Brain health'],
    typicalDosage: '500-1000mg daily',
    timing: 'with-food',
    tags: ['general-wellness', 'focus'],
  },
  {
    id: 'elderberry',
    name: 'Elderberry',
    icon: '🫐',
    category: 'herbal',
    description: 'Traditional immune support rich in antioxidants and vitamins.',
    benefits: ['Immune boost', 'Antioxidant', 'Cold & flu support'],
    typicalDosage: '500-1000mg daily',
    timing: 'any',
    tags: ['immunity', 'general-wellness'],
  },
  {
    id: 'ginger',
    name: 'Ginger',
    icon: '🫚',
    category: 'herbal',
    description: 'Supports digestive comfort and has natural anti-inflammatory properties.',
    benefits: ['Digestive aid', 'Nausea relief', 'Anti-inflammatory'],
    typicalDosage: '250-500mg daily',
    timing: 'with-food',
    tags: ['digestion', 'general-wellness'],
  },
  {
    id: 'valerian-root',
    name: 'Valerian Root',
    icon: '🌸',
    category: 'herbal',
    description: 'A calming herb traditionally used to support restful sleep.',
    benefits: ['Sleep support', 'Relaxation', 'Calm nerves'],
    typicalDosage: '300-600mg before bed',
    timing: 'evening',
    tags: ['sleep', 'stress-relief'],
  },
  {
    id: 'chamomile',
    name: 'Chamomile',
    icon: '🌼',
    category: 'herbal',
    description: 'A gentle herb promoting relaxation and digestive comfort.',
    benefits: ['Relaxation', 'Sleep aid', 'Digestive soothing'],
    typicalDosage: '400-1600mg daily',
    timing: 'evening',
    tags: ['sleep', 'stress-relief', 'digestion'],
  },
  {
    id: 'echinacea',
    name: 'Echinacea',
    icon: '🌺',
    category: 'herbal',
    description: 'A traditional immune booster, especially during cold season.',
    benefits: ['Immune support', 'Cold prevention', 'Recovery aid'],
    typicalDosage: '300-500mg daily',
    timing: 'any',
    tags: ['immunity'],
  },
  {
    id: 'holy-basil',
    name: 'Holy Basil (Tulsi)',
    icon: '🌿',
    category: 'herbal',
    description: 'An adaptogen supporting stress response and mental clarity.',
    benefits: ['Stress relief', 'Mental clarity', 'Respiratory health'],
    typicalDosage: '300-600mg daily',
    timing: 'morning',
    tags: ['stress-relief', 'focus', 'immunity'],
  },
  {
    id: 'milk-thistle',
    name: 'Milk Thistle',
    icon: '🌸',
    category: 'herbal',
    description: 'Supports liver health and natural detoxification processes.',
    benefits: ['Liver support', 'Detox aid', 'Antioxidant'],
    typicalDosage: '150-300mg daily',
    timing: 'with-food',
    tags: ['general-wellness'],
  },
  {
    id: 'maca-root',
    name: 'Maca Root',
    icon: '🥔',
    category: 'herbal',
    description: 'A Peruvian superfood supporting energy, mood, and hormonal balance.',
    benefits: ['Energy boost', 'Hormone balance', 'Libido support'],
    typicalDosage: '1500-3000mg daily',
    timing: 'morning',
    tags: ['energy', 'general-wellness'],
  },
  {
    id: 'ginkgo-biloba',
    name: 'Ginkgo Biloba',
    icon: '🍃',
    category: 'herbal',
    description: 'Supports cognitive function and healthy blood circulation.',
    benefits: ['Memory support', 'Circulation', 'Brain health'],
    typicalDosage: '120-240mg daily',
    timing: 'morning',
    tags: ['focus', 'general-wellness'],
  },
  {
    id: 'passionflower',
    name: 'Passionflower',
    icon: '💜',
    category: 'herbal',
    description: 'A calming herb that promotes relaxation and supports sleep.',
    benefits: ['Anxiety relief', 'Sleep support', 'Muscle relaxation'],
    typicalDosage: '250-500mg daily',
    timing: 'evening',
    tags: ['sleep', 'stress-relief'],
  },

  // SPECIALTY
  {
    id: 'collagen',
    name: 'Collagen Peptides',
    icon: '✨',
    category: 'specialty',
    description: 'Supports skin elasticity, hair strength, and joint health.',
    benefits: ['Skin elasticity', 'Hair & nails', 'Joint support'],
    typicalDosage: '5-15g daily',
    timing: 'any',
    tags: ['skin-health', 'general-wellness'],
  },
  {
    id: 'coq10',
    name: 'CoQ10',
    icon: '❤️',
    category: 'specialty',
    description: 'A coenzyme supporting heart health and cellular energy production.',
    benefits: ['Heart health', 'Energy production', 'Antioxidant'],
    typicalDosage: '100-200mg daily',
    timing: 'with-food',
    tags: ['energy', 'general-wellness'],
  },
  {
    id: 'l-theanine',
    name: 'L-Theanine',
    icon: '🍵',
    category: 'specialty',
    description: 'An amino acid from tea promoting calm focus without drowsiness.',
    benefits: ['Calm focus', 'Relaxation', 'Mental clarity'],
    typicalDosage: '100-200mg daily',
    timing: 'any',
    tags: ['focus', 'stress-relief'],
  },
  {
    id: 'melatonin',
    name: 'Melatonin',
    icon: '🌙',
    category: 'specialty',
    description: 'A natural sleep hormone supporting healthy sleep cycles.',
    benefits: ['Sleep onset', 'Jet lag relief', 'Sleep quality'],
    typicalDosage: '0.5-5mg before bed',
    timing: 'evening',
    tags: ['sleep'],
  },
  {
    id: 'spirulina',
    name: 'Spirulina',
    icon: '🌊',
    category: 'specialty',
    description: 'A nutrient-dense blue-green algae packed with protein and vitamins.',
    benefits: ['Nutrient boost', 'Detox support', 'Energy'],
    typicalDosage: '1-3g daily',
    timing: 'morning',
    tags: ['energy', 'immunity', 'general-wellness'],
  },
  {
    id: 'chlorella',
    name: 'Chlorella',
    icon: '💚',
    category: 'specialty',
    description: 'A green algae supporting detoxification and immune function.',
    benefits: ['Detoxification', 'Immune support', 'Nutrient-rich'],
    typicalDosage: '2-3g daily',
    timing: 'morning',
    tags: ['immunity', 'general-wellness'],
  },
  {
    id: 'lions-mane',
    name: "Lion's Mane",
    icon: '🍄',
    category: 'specialty',
    description: 'A medicinal mushroom supporting brain health and nerve function.',
    benefits: ['Brain health', 'Focus', 'Nerve support'],
    typicalDosage: '500-1000mg daily',
    timing: 'morning',
    tags: ['focus', 'general-wellness'],
  },
  {
    id: 'reishi',
    name: 'Reishi Mushroom',
    icon: '🍄',
    category: 'specialty',
    description: 'An adaptogenic mushroom supporting immune function and relaxation.',
    benefits: ['Immune modulation', 'Stress relief', 'Sleep support'],
    typicalDosage: '1000-1500mg daily',
    timing: 'evening',
    tags: ['immunity', 'stress-relief', 'sleep'],
  },
  {
    id: 'quercetin',
    name: 'Quercetin',
    icon: '🍎',
    category: 'specialty',
    description: 'A plant flavonoid with powerful antioxidant and anti-inflammatory effects.',
    benefits: ['Allergy support', 'Antioxidant', 'Immune health'],
    typicalDosage: '500-1000mg daily',
    timing: 'with-food',
    tags: ['immunity', 'general-wellness'],
  },
  {
    id: 'resveratrol',
    name: 'Resveratrol',
    icon: '🍇',
    category: 'specialty',
    description: 'A polyphenol found in grapes supporting heart health and longevity.',
    benefits: ['Heart health', 'Antioxidant', 'Cellular health'],
    typicalDosage: '150-500mg daily',
    timing: 'with-food',
    tags: ['general-wellness'],
  },
  {
    id: 'alpha-lipoic-acid',
    name: 'Alpha-Lipoic Acid',
    icon: '🔋',
    category: 'specialty',
    description: 'A powerful antioxidant supporting energy metabolism and blood sugar.',
    benefits: ['Energy metabolism', 'Antioxidant', 'Blood sugar support'],
    typicalDosage: '300-600mg daily',
    timing: 'with-food',
    tags: ['energy', 'general-wellness'],
  },
  {
    id: 'n-acetyl-cysteine',
    name: 'NAC',
    icon: '🛡️',
    category: 'specialty',
    description: 'Supports liver health and glutathione production for detoxification.',
    benefits: ['Liver support', 'Antioxidant boost', 'Respiratory health'],
    typicalDosage: '600-1200mg daily',
    timing: 'any',
    tags: ['immunity', 'general-wellness'],
  },
  {
    id: 'digestive-enzymes',
    name: 'Digestive Enzymes',
    icon: '🍽️',
    category: 'specialty',
    description: 'Supports the breakdown and absorption of nutrients from food.',
    benefits: ['Nutrient absorption', 'Digestive comfort', 'Bloating relief'],
    typicalDosage: '1 capsule with meals',
    timing: 'with-food',
    tags: ['digestion'],
  },
];

// Helper function to get supplements by category
export const getSupplementsByCategory = (category: string): SupplementInfo[] => {
  return SUPPLEMENT_CATALOG.filter(s => s.category === category);
};

// Helper function to get supplements by wellness goal
export const getSupplementsByGoal = (goal: WellnessGoal): SupplementInfo[] => {
  return SUPPLEMENT_CATALOG.filter(s => s.tags.includes(goal));
};

// Helper function to get supplement by ID
export const getSupplementById = (id: string): SupplementInfo | undefined => {
  return SUPPLEMENT_CATALOG.find(s => s.id === id);
};
